language: haskell

addons:
  apt:
    packages:
    - cabal-install-2.0
    - ghc-8.4.3
    - alex-3.1.7
    - happy-1.19.5

before_install:
  - export PATH=/opt/ghc/8.4.3/bin:/opt/cabal/2.2/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

ghc:
  - "8.2.2"
  - "8.4.3"
  - "8.6.4"