version: "2.4"
services:
  lightsup:
    restart: always
    build: .
    ports:
      - "12768:80"
    mem_limit: 1024M
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    expose:
      - "6379"
    mem_limit: 1024M
    volumes:
      - lightsup-redis-data:/data

volumes:
  lightsup-redis-data:
